### ISSUE TITLE
中英文无法切换

### ISSUE THREAD

**Issue by junorz** [accreator/Yixin-Board#2]
默认英文界面，但是点选简体中文之后原窗口关闭，出来的新窗口依然是英文。

**Comment by accreator** [comment]
That is because you installed Yixin-Board to the system directory (Program Files folder), and any changes to that directory require administrator privileges.  So if you would like to modify its settings, you need to run Yixin-Board with administrator privileges, or you should install Yixin-Board to non-system directory.
